# Usage (example):
#   docker build -t magma-cross/aflplusplus/libpng \
#       --build-arg fuzzer=aflplusplus \
#       --build-arg target=libpng \
#       --build-arg target_arch=arm-linux-gnueabihf \
#       --build-arg user_id="$(id -u)" \
#       --build-arg group_id="$(id -g)" \
#       --build-arg canaries=1 \
#       -f DOCKERFILE_PIRATE .

FROM ubuntu:18.04

################################################################################
# I. Environment Setup
################################################################################
ARG DEBIAN_FRONTEND=noninteractive

## Magma directory hierarchy
# magma_root is relative to the docker-build's working directory
# The Docker image must be built in the root of the magma directory
# So we must provide the context usen $MAGMA_R
ENV HOST_CONTEXT_ROOT=./

ENV MAGMA_R=/magma

ARG fuzzer=aflplusplus
ARG target=libpng
ARG target_arch=arm-linux-gnueabihf
ARG user_id=1000
ARG group_id=1000
ARG isan
ARG harden
ARG canaries
ARG fixes

ENV FUZZER_NAME=${fuzzer}
ENV FUZZER=${MAGMA_R}/fuzzers/${FUZZER_NAME}
ENV TARGET_NAME=${target}
ENV TARGET=${MAGMA_R}/targets/${TARGET_NAME}
ENV TARGET_ARCH=${target_arch}
ENV USERID=${user_id}
ENV GROUPID=${group_id}

ENV MAGMA=${MAGMA_R}/magma
ENV OUT=/magma_out
ENV SHARED=/magma_shared
ENV DEPS_PATH=/magma_deps
ENV QEMU_SYSROOT=/magma_sysroot

# Compiler Variables x86
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++
ENV LD=/usr/bin/ld
ENV AR=/usr/bin/ar
ENV AS=/usr/bin/as
ENV NM=/usr/bin/nm
ENV RANLIB=/usr/bin/ranlib

# Compiler variables cross
ENV TARGET_CC=/usr/bin/${TARGET_ARCH}-gcc
ENV TARGET_CXX=/usr/bin/${TARGET_ARCH}-g++
ENV TARGET_AR=/usr/bin/${TARGET_ARCH}-ar
ENV TARGET_LD=/usr/bin/${TARGET_ARCH}-ld
ENV TARGET_NM=/usr/bin/${TARGET_ARCH}-nm
ENV TARGET_RANLIB=/usr/bin/${TARGET_ARCH}-ranlib

ENV QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
ENV LD_LIBRARY_PATH=${OUT}

################################################################################
# II. Initial OS and environment setup
################################################################################
# Use bash. Ubuntu defaults to dash!
SHELL ["/bin/bash", "-c"]

USER root:root

RUN apt-get update && apt-get install -y sudo

# Install cross-compilation toolchain and QEMU
# Note: Using DEBIAN_FRONTEND only for this RUN to avoid tzdata prompts
RUN apt-get install -y \
    gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
    gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
    qemu-user qemu-user-static



# Add ARM32 repositories
RUN dpkg --add-architecture armhf

RUN echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ bionic main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ bionic-security main restricted universe multiverse" >> /etc/apt/sources.list

RUN apt-get update

# Debug dependencies
RUN apt-get install -y \
    file vim neovim

RUN mkdir -p /home && \
	groupadd -g ${GROUPID} magma && \
	useradd -l -u ${USERID} -K UMASK=0000 -d /home -g magma magma && \
	chown magma:magma /home
RUN	echo "magma:magma" | chpasswd && \
    usermod -a -G sudo magma && \
    echo "magma ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/magma && \
    chmod 0440 /etc/sudoers.d/magma

RUN mkdir -p ${OUT} ${SHARED} ${DEPS_PATH} ${QEMU_SYSROOT} && \
    chown magma:magma ${OUT} ${SHARED} ${DEPS_PATH} ${QEMU_SYSROOT} && \
    chmod 755 ${OUT} ${SHARED} ${DEPS_PATH} ${QEMU_SYSROOT}

RUN mkdir -p ${DEPS_PATH}/{lib,include} ${QEMU_SYSROOT}/{lib,usr/lib}


################################################################################
# III. Magma Monitor
################################################################################
USER root:root
RUN mkdir -p ${MAGMA} && chown magma:magma ${MAGMA}
COPY --chown=magma:magma ${HOST_CONTEXT_ROOT}/magma ${MAGMA}
# Installs Magma dependencies
RUN ${MAGMA}/preinstall.sh
USER magma:magma
# Compiles the  Magma monitor
RUN ${MAGMA}/prebuild.sh

################################################################################
# IV. Fuzzer
################################################################################
USER root:root
RUN mkdir -p ${FUZZER} && chown magma:magma ${FUZZER}
COPY --chown=magma:magma ${HOST_CONTEXT_ROOT}/fuzzers/${FUZZER_NAME} ${FUZZER}
# Install fuzzer dependencies
RUN ${FUZZER}/preinstall.sh

USER magma:magma
# Retrieves fuzzer source code.
RUN ${FUZZER}/fetch.sh
# Compiles the fuzzer binaries
RUN ${FUZZER}/build.sh

#######################################
# Build AFL++ QEMU mode
#######################################
# Note: This Section is specific to AFL++
USER root:root
RUN apt-get install -y \
	ninja-build pkg-config libglib2.0-dev build-essential python3-dev \
	automake git flex bison libpixman-1-dev python3-setuptools

USER magma:magma
RUN cd ${FUZZER}/repo/qemu_mode && \
    CROSS=${TARGET_CC} CPU_TARGET=${TARGET_ARCH%%-*} ./build_qemu_support.sh
# CAUTION: Shell parameter expansion works for most architectures, but not all!
#          (As this is primarly for arm, I don't want to bloat the Dockerfile.)


#===============================================================================
# [INFO]: From now on everything is cross compiled, so we can set CC, CXX, etc.
#         to the target architecture
#===============================================================================
ENV CC=${TARGET_CC}
ENV CXX=${TARGET_CXX}
ENV AR=${TARGET_AR}
ENV LD=${TARGET_LD}
ENV NM=${TARGET_NM}
ENV RANLIB=${TARGET_RANLIB}
#===============================================================================

########################################
# Build AFL++ QEMU Driver
########################################
# Note: This Section is specific to AFL++
USER magma:magma
COPY --chown=magma:magma \
    ${HOST_CONTEXT_ROOT}/tools/pirate/scripts/aflpp_driver_cross.sh \
    ${FUZZER}
# Cross compile AFL++ driver
RUN ${FUZZER}/aflpp_driver_cross.sh
ENV LIBS="${OUT}/driver/libAFLQemuDriver.a"

################################################################################
# V. Magma instrumentation
################################################################################
# Pass magma intrumentation to flags
ENV MAGMA_BUILD_FLAGS="-include ${MAGMA}/src/canary.h \
    ${canaries:+-DMAGMA_ENABLE_CANARIES} \
    ${fixes:+-DMAGMA_ENABLE_FIXES} \
    ${isan:+-DMAGMA_FATAL_CANARIES} \
    ${harden:+-DMAGMA_HARDEN_CANARIES}"
ENV BUILD_FLAGS="-g -O0 -fPIC"

ENV CFLAGS="${MAGMA_BUILD_FLAGS} ${BUILD_FLAGS}"
ENV CXXFLAGS="${MAGMA_BUILD_FLAGS} ${BUILD_FLAGS}"
ENV LDFLAGS="-L${OUT} -g"
ENV LIBS="${LIBS} -l:magma.o -lrt"

USER magma:magma
COPY --chown=magma:magma \
    ${HOST_CONTEXT_ROOT}/tools/pirate/scripts/magma_build_cross.sh \
    ${MAGMA}

# Cross compile Magma runtime library $OUT/magma.o
RUN ${MAGMA}/magma_build_cross.sh

################################################################################
# VI. Target
################################################################################
# -> replaces ${FUZZER}/instrument.sh, as we don't have source code instrument.
#
# I.e. Targets are not built with the afl compiler (afl-clang-fast++) but with
# a "normal" cross-compiler
################################################################################
USER root:root
RUN mkdir -p ${FUZZER} && chown magma:magma ${FUZZER}
COPY --chown=magma:magma ${HOST_CONTEXT_ROOT}/targets/${TARGET_NAME} ${TARGET}
COPY --chown=magma:magma \
    ${HOST_CONTEXT_ROOT}/tools/pirate/scripts/${TARGET_NAME}_build_cross.sh \
    ${TARGET}

# Install cross-compiled runtime dependencies (only for libpng for now)
RUN apt-get install -y zlib1g-dev:armhf

# Install target runtime and build dependencies
RUN ${TARGET}/preinstall.sh
# NOTE: Cross-compiled runtime dependencies are
#       installed in the RUN line above.

USER magma:magma
# Retrieves target source code
RUN ${TARGET}/fetch.sh
# Forward ports bugs
RUN ${MAGMA}/apply_patches.sh


RUN ${TARGET}/${TARGET_NAME}_build_cross.sh

################DEBUG###########################################
COPY --chown=magma:magma ${HOST_CONTEXT_ROOT}/tools/pirate ${MAGMA_R}/pirate


ENTRYPOINT "/bin/bash"